20250815: [83.42227820265518]
20250816: [83.16180564301004]
20250817: [84.52922856011482]
20250818: [83.96683247717141]
20250819: [82.50182823138398]
20250820: [82.69208383327609]
20250821: [81.93539039086474]
20250822: [80.75589325083922]
20250823: [82.4571111477334]
20250824: [77.8842243187191]
20250825: [74.47202480001465]
20250826: [81.24268424392164]
20250827: [80.87210308083823]
20250828: [79.09200464530493]
20250829: [80.76660856190489]
20250830: [81.90612734964628]
20250831: [81.98217214898384]
20250901: [80.99045606478501]
20250902: [83.85192344305999]
20250903: [83.17584922123574]
20250904: [81.35260727336866]
20250905: [81.04154702490914]
20250906: [81.66679753735937]
20250907: [83.2421241303603]
20250908: [82.42257699574692]
20250909: [78.73784304112027]
20250910: [76.87642729915429]
20250911: [80.01365656289863]
20250912: [79.6584918193908]
20250913: [76.64848675639693]
20250914: [77.94032893791294]
20250915: [76.77834839094238]
20250916: [78.7951846767718]
20250917: [79.61066392870626]
20250918: [82.65179171974768]
20250919: [80.65204635798499]
20250920: [81.033314813448]
20250921: [79.07016343918028]
20250922: [79.500014511871]
20250923: [80.34080353237353]
20250924: [76.96969173896557]
20250926: [80.22292572380121]
20250927: [81.60298158095533]
20250928: [81.60222497807838]
20250929: [77.79645322272857]
20250930: [73.93257242968485]
20251001: [74.57383543083898]
20251002: [75.91532656388532]
20251003: [79.29553743841302]
20251004: [80.7823343582768]
20251005: [80.39011487919117]
20251006: [79.02802945907689]
20251007: [77.66939717817246]
20251008: [79.4583738552542]
20251009: [73.97369706095355]
20251010: [78.4887519188316]
20251011: [73.25064689597039]
20251012: [72.46759831742959]
20251013: [78.5650530909904]
20251014: [82.41754107322387]
20251015: [82.8763098608856]
20251016: [82.31788569107609]
20251017: [82.40734458221019]
20251018: [79.67057304632169]
20251019: [78.27359422834733]
20251020: [76.99638345502022]
20251021: [76.83413503819231]
20251022: [79.39393399846054]
20251023: [79.89548764707764]
20251024: [79.69277091443689]
20251025: [79.47317076347967]
20251026: [79.64910834601423]
20251027: [81.89869304326801]
20251028: [79.64110932176337]
20251029: [81.95790503084541]
20251030: [82.5017268059852]
20251031: [83.31525335246062]
20251101: [80.06004784178836]
20251102: [80.8582176973573]
20251103: [79.8204977774236]
20251104: [79.69414316509621]
20251105: [83.3073412966577]
20251106: [83.5851473491844]
20251107: [82.81475468983817]
20251108: [83.87749566255329]
20251109: [82.5156370916588]
20251110: [85.0647989952018]
20251111: [82.57531302722673]
20251112: [81.82926311415854]
20251113: [83.19985023525494]
20251114: [81.66105858483103]
20251115: [84.76375571306143]
20251117: [83.3435525402532]
20251118: [80.97220658276814]
20251119: [84.52123063534]
20251120: [80.51122554352146]
20251121: [87.86395585648513]
