20251012: [72.46759831742959]
20251013: [78.5650530909904]
20251014: [82.41754107322387]
20251015: [82.8763098608856]
20251016: [82.31788569107609]
20251017: [82.40734458221019]
20251018: [79.67057304632169]
20251019: [78.27359422834733]
20251020: [76.99638345502022]
20251021: [76.83413503819231]
20251022: [79.39393399846054]
20251023: [79.89548764707764]
20251024: [79.69277091443689]
20251025: [79.47317076347967]
20251026: [79.64910834601423]
20251027: [81.89869304326801]
20251028: [79.64110932176337]
20251029: [81.95790503084541]
20251030: [82.5017268059852]
20251031: [83.31525335246062]
20251101: [80.06004784178836]
20251102: [80.8582176973573]
20251103: [79.8204977774236]
20251104: [79.69414316509621]
20251105: [83.3073412966577]
20251106: [83.5851473491844]
20251107: [82.81475468983817]
20251108: [83.87749566255329]
20251109: [82.5156370916588]
