20251024: [79.69277091443689]
20251025: [79.47317076347967]
20251026: [79.64910834601423]
20251027: [81.89869304326801]
20251028: [79.64110932176337]
20251029: [81.95790503084541]
20251030: [82.5017268059852]
20251031: [83.31525335246062]
20251101: [80.06004784178836]
20251102: [80.8582176973573]
20251103: [79.8204977774236]
20251104: [79.69414316509621]
20251105: [83.3073412966577]
20251106: [83.5851473491844]
20251107: [82.81475468983817]
20251108: [83.87749566255329]
