20250708: [86.18264551232812]
20250709: [90.20822476759076]
20250710: [89.05207431747648]
20250711: [82.32179861025179]
20250712: [83.57667653170847]
20250713: [86.34520492778148]
20250714: [89.41348173211409]
20250715: [82.14016512154006]
20250716: [84.20734417542678]
20250717: [83.26963747594178]
20250718: [82.16682897369463]
20250719: [83.76402011693585]
20250720: [84.13960314171638]
20250721: [76.41893510159258]
20250722: [75.20598184004226]
20250723: [83.27883416345222]
20250724: [77.75836824007592]
20250725: [82.5419615394195]
20250726: [81.99514386505945]
20250727: [82.27582637741318]
20250728: [82.7120853387235]
20250729: [83.50721818947662]
20250730: [82.94569613038676]
20250731: [84.23343763846161]
20250801: [84.38325559405321]
20250802: [83.74418594493955]
20250803: [83.67772247104709]
20250804: [82.96103849545119]
20250805: [79.79841848177401]
20250806: [81.96358567750337]
20250807: [81.14400841682318]
20250808: [83.74132526852411]
20250809: [81.87517454128202]
20250810: [82.904874897811]
20250811: [81.01689208460257]
20250812: [82.1726015060334]
20250813: [83.0022487113392]
20250814: [84.83312251631614]
20250815: [83.42227820265518]
20250816: [83.16180564301004]
20250817: [84.52922856011482]
20250818: [83.96683247717141]
20250819: [82.50182823138398]
20250820: [82.69208383327609]
20250821: [81.93539039086474]
20250822: [80.75589325083922]
20250823: [82.4571111477334]
20250824: [77.8842243187191]
20250825: [74.47202480001465]
20250826: [81.24268424392164]
20250827: [80.87210308083823]
20250828: [79.09200464530493]
20250829: [80.76660856190489]
20250830: [81.90612734964628]
20250831: [81.98217214898384]
20250901: [80.99045606478501]
20250902: [83.85192344305999]
20250903: [83.17584922123574]
20250904: [81.35260727336866]
20250905: [81.04154702490914]
20250906: [81.66679753735937]
20250907: [83.2421241303603]
20250908: [82.42257699574692]
20250909: [78.73784304112027]
20250910: [76.87642729915429]
20250911: [80.01365656289863]
20250912: [79.6584918193908]
20250913: [76.64848675639693]
20250914: [77.94032893791294]
20250915: [76.77834839094238]
20250916: [78.7951846767718]
20250917: [79.61066392870626]
20250918: [82.65179171974768]
20250919: [80.65204635798499]
20250920: [81.033314813448]
20250921: [79.07016343918028]
20250922: [79.500014511871]
20250923: [80.34080353237353]
20250924: [76.96969173896557]
20250926: [80.22292572380121]
20250927: [81.60298158095533]
20250928: [81.60222497807838]
20250929: [77.79645322272857]
20250930: [73.93257242968485]
20251001: [74.57383543083898]
20251002: [75.91532656388532]
20251003: [79.29553743841302]
20251004: [80.7823343582768]
20251005: [80.39011487919117]
20251006: [79.02802945907689]
20251007: [77.66939717817246]
20251008: [79.4583738552542]
20251009: [73.97369706095355]
20251010: [78.4887519188316]
20251011: [73.25064689597039]
20251012: [72.46759831742959]
20251013: [78.5650530909904]
20251014: [82.41754107322387]
20251015: [82.8763098608856]
20251016: [82.31788569107609]
20251017: [82.40734458221019]
20251018: [79.67057304632169]
20251019: [78.27359422834733]
20251020: [76.99638345502022]
20251021: [76.83413503819231]
20251022: [79.39393399846054]
20251023: [79.89548764707764]
20251024: [79.69277091443689]
20251025: [79.47317076347967]
20251026: [79.64910834601423]
20251027: [81.89869304326801]
20251028: [79.64110932176337]
20251029: [81.95790503084541]
20251030: [82.5017268059852]
20251031: [83.31525335246062]
20251101: [80.06004784178836]
20251102: [80.8582176973573]
20251103: [79.8204977774236]
20251104: [79.69414316509621]
20251105: [83.3073412966577]
20251106: [83.5851473491844]
20251107: [82.81475468983817]
20251108: [83.87749566255329]
20251109: [82.5156370916588]
20251110: [85.0647989952018]
20251111: [82.57531302722673]
20251112: [81.82926311415854]
20251113: [83.19985023525494]
20251114: [81.66105858483103]
20251115: [84.76375571306143]
20251117: [83.3435525402532]
20251118: [80.97220658276814]
20251119: [84.52123063534]
20251120: [80.51122554352146]
20251121: [87.86395585648513]
20251124: [85.77967983544237]
20251125: [86.00618624480074]
20251126: [91.38257842876428]
20251127: [90.9389651130489]
20251128: [90.15234405435831]
20251129: [87.6764135546032]
20251130: [89.74552313742875]
20251201: [91.62928425100992]
20251202: [89.86318964821736]
20251203: [90.7523917821784]
20251204: [81.35407426579236]
20251205: [82.41898346050452]
20251206: [90.20978599849447]
20251207: [74.25627146100388]
20251208: [90.11357577755494]
20251209: [77.90575432426483]
20251210: [89.3261544645864]
20251211: [86.62655156495335]
20251212: [81.40392179220238]
20251213: [88.48176771395816]
20251214: [88.53327458279588]
20251215: [88.82951172558484]
20251216: [87.6840316261051]
20251217: [93.38649212703477]
20251218: [91.07136911483637]
20251219: [90.66589117713468]
20251220: [91.98093395260352]
20251221: [90.45569326360898]
20251222: [91.23686298128396]
20251223: [89.11392028544557]
20251224: [92.96258351977939]
20251225: [88.8992180286586]
20251226: [87.12555799324151]
20251227: [89.18340716682071]
20251228: [88.78458937507246]
20251229: [86.4773048803451]
20251230: [87.19978066499567]
20251231: [85.15648164920354]
20260101: [87.46407115585251]
20260102: [85.32712176294845]
20260103: [86.94754377290514]
20260104: [87.6061091642032]
20260105: [82.9002278991907]
20260106: [84.82902083930136]
20260107: [88.43992060567413]
20260108: [84.36832406734871]
20260109: [85.00433863864723]
20260110: [87.24868522644853]
20260111: [86.99861870664013]
20260112: [87.7917569392196]
20260113: [88.56125640079034]
20260114: [88.29467448517337]
20260115: [88.33997446574786]
20260116: [90.3800869540917]
20260117: [88.56394452089572]
20260118: [89.49059639404533]
20260119: [88.71887433130867]
20260120: [85.75094875811715]
20260121: [86.27988854522201]
20260122: [86.05885083649439]
20260123: [92.50414163256515]
20260124: [88.09541665695798]
20260125: [88.25625389193522]
20260126: [89.88124318404103]
20260127: [89.93933448322538]
20260128: [94.42244452886469]
20260129: [94.04196576399706]
20260130: [94.25961582692231]
