20250708: [7540064.616202609]
20250709: [7107405.283643136]
20250710: [7710274.817341916]
20250711: [7642828.491438546]
20250712: [7497061.180294449]
20250713: [7390664.916464274]
20250714: [7686437.438740199]
20250715: [7878592.4330857545]
20250716: [7580351.691456121]
20250717: [7647884.1559022935]
20250718: [7595336.663612745]
20250719: [7531934.794066676]
20250720: [7488636.530052689]
20250721: [7310183.791669827]
20250722: [7176641.502431355]
20250723: [7811956.508723122]
20250724: [7493602.965453337]
20250725: [7317278.193729756]
20250726: [7634332.404756308]
20250727: [7698479.594586502]
20250728: [7701569.198480151]
20250729: [7383073.182074801]
20250730: [7344607.855120429]
20250731: [7283335.476698875]
20250801: [7081162.619518682]
20250802: [7522392.752416012]
20250803: [7666247.911488617]
20250804: [7668895.110588022]
20250805: [7329285.492456353]
20250806: [7486717.667082184]
20250807: [7627461.805225624]
20250808: [7764444.569230809]
20250809: [7733764.021568858]
20250810: [7694530.055108596]
20250811: [7508929.796799606]
20250812: [7807507.368976247]
20250813: [7629974.188369205]
20250814: [7633194.186486972]
20250815: [7728936.153085687]
20250816: [7974111.176004178]
20250817: [7868968.156995424]
20250818: [7662774.354347693]
20250819: [7784507.934613682]
20250820: [7652361.418660329]
20250821: [7745673.9837415125]
20250822: [7703141.467493539]
20250823: [8003026.8190722205]
20250824: [7738923.264350215]
20250825: [7905887.82841801]
20250826: [7562973.745713488]
20250827: [7485515.882123981]
20250828: [7740937.931757173]
20250829: [7520298.394043174]
20250830: [7134887.738317041]
20250831: [7394981.893290252]
20250901: [7176282.558401078]
20250902: [7823119.775452166]
20250903: [7367988.325675967]
20250904: [7567548.773527671]
20250905: [7431978.457574966]
20250906: [7686404.26994722]
20250907: [7666592.081784888]
20250908: [7711804.987885851]
20250909: [6444072.452903785]
20250910: [6872200.700511868]
20250911: [7367652.679974555]
20250912: [7443511.957972735]
20250913: [7399726.162065003]
20250914: [7550563.640791121]
20250915: [7542986.845530286]
20250916: [7654036.159079907]
20250917: [7756991.022790971]
20250918: [7007863.478352864]
20250919: [7065585.417283027]
20250920: [6838221.668914802]
20250921: [7181139.480816094]
20250922: [7327395.60875548]
20250923: [7552300.191526628]
20250924: [7802553.987152377]
20250926: [7773737.340977673]
20250927: [7766009.695063163]
20250928: [7680368.885004105]
20250929: [7636852.4272069475]
20250930: [7085499.635269653]
20251001: [7484947.713391372]
20251002: [7383724.849450192]
20251003: [7656401.5831310125]
20251004: [7772840.06183981]
20251005: [7340245.972183053]
20251006: [7489729.778875384]
20251007: [7844155.203744909]
20251008: [7588824.6730355555]
20251009: [7529224.011288783]
20251010: [7417179.362323435]
20251011: [7185829.1137265405]
20251012: [7393751.5651736455]
20251013: [7809698.668155951]
20251014: [7896439.830476417]
20251015: [7979615.271420311]
20251016: [7108205.266422834]
20251017: [7145244.319371267]
20251018: [7690747.000131539]
20251019: [7422549.806586569]
20251020: [7386802.203069889]
20251021: [7623765.131850785]
20251022: [7855906.422684877]
20251023: [7817502.363565975]
20251024: [7871919.572232763]
20251025: [7536688.906896139]
20251026: [7475914.90752792]
20251027: [7508463.9078257345]
20251028: [7558019.691833947]
20251029: [7105427.4009364275]
20251030: [7347899.578831099]
20251031: [7445062.499681384]
20251101: [6784151.29101118]
20251102: [6825154.675667853]
20251103: [6788127.751143565]
20251104: [6832147.224844349]
20251105: [5522892.633302725]
20251106: [7736174.3202184085]
20251107: [7304032.87190469]
20251108: [7505964.863917534]
20251109: [7676582.60576439]
20251110: [7697120.315583078]
20251111: [7299520.992626209]
20251112: [7636132.815398388]
20251113: [7279754.52163235]
20251114: [7616891.702918431]
20251115: [7574801.397203699]
20251117: [7070326.319625912]
20251118: [7106770.897177384]
20251119: [7826507.445148936]
20251120: [7561489.880975813]
20251121: [7621541.093518739]
20251124: [7340497.050783358]
20251125: [7389309.340302723]
20251126: [7899075.443024488]
20251127: [7826684.423750967]
20251128: [7828125.112509127]
20251129: [7732668.923013862]
20251130: [7690480.858810911]
20251201: [7584382.928950261]
20251202: [7358105.45784104]
20251203: [7704115.843482806]
20251204: [8120512.970276633]
20251205: [7719975.466792009]
20251206: [7824168.925749067]
20251207: [7872928.022621115]
