20251020: [7386802.203069889]
20251021: [7623765.131850785]
20251022: [7855906.422684877]
20251023: [7817502.363565975]
20251024: [7871919.572232763]
20251025: [7536688.906896139]
20251026: [7475914.90752792]
20251027: [7508463.9078257345]
20251028: [7558019.691833947]
20251029: [7105427.4009364275]
20251030: [7347899.578831099]
20251031: [7445062.499681384]
20251101: [6784151.29101118]
20251102: [6825154.675667853]
20251103: [6788127.751143565]
20251104: [6832147.224844349]
20251105: [5522892.633302725]
20251106: [7736174.3202184085]
20251107: [7304032.87190469]
20251108: [7505964.863917534]
