20250921: [7181139.480816094]
20250922: [7327395.60875548]
20250923: [7552300.191526628]
20250924: [7802553.987152377]
20250926: [7773737.340977673]
20250927: [7766009.695063163]
20250928: [7680368.885004105]
20250929: [7636852.4272069475]
20250930: [7085499.635269653]
20251001: [7484947.713391372]
20251002: [7383724.849450192]
20251003: [7656401.5831310125]
20251004: [7772840.06183981]
20251005: [7340245.972183053]
20251006: [7489729.778875384]
20251007: [7844155.203744909]
20251008: [7588824.6730355555]
20251009: [7529224.011288783]
20251010: [7417179.362323435]
20251011: [7185829.1137265405]
20251012: [7393751.5651736455]
20251013: [7809698.668155951]
20251014: [7896439.830476417]
20251015: [7979615.271420311]
20251016: [7108205.266422834]
20251017: [7145244.319371267]
20251018: [7690747.000131539]
20251019: [7422549.806586569]
20251020: [7386802.203069889]
20251021: [7623765.131850785]
20251022: [7855906.422684877]
20251023: [7817502.363565975]
20251024: [7871919.572232763]
20251025: [7536688.906896139]
20251026: [7475914.90752792]
20251027: [7508463.9078257345]
20251028: [7558019.691833947]
20251029: [7105427.4009364275]
20251030: [7347899.578831099]
20251031: [7445062.499681384]
20251101: [6784151.29101118]
20251102: [6825154.675667853]
20251103: [6788127.751143565]
20251104: [6832147.224844349]
20251105: [5522892.633302725]
20251106: [7736174.3202184085]
20251107: [7304032.87190469]
20251108: [7505964.863917534]
20251109: [7676582.60576439]
20251110: [7697120.315583078]
20251111: [7299520.992626209]
20251112: [7636132.815398388]
20251113: [7279754.52163235]
20251114: [7616891.702918431]
