20251031: [7445062.499681384]
20251101: [6784151.29101118]
20251102: [6825154.675667853]
20251103: [6788127.751143565]
20251104: [6832147.224844349]
20251105: [5522892.633302725]
20251106: [7736174.3202184085]
20251107: [7304032.87190469]
