20250719: [3.801300194405017]
20250720: [3.6383001629198324]
20250721: [4.394945376890341]
20250722: [4.321499818288353]
20250723: [4.313813276378807]
20250724: [4.352434226060366]
20250725: [4.321472094366939]
20250726: [4.411964983486572]
20250727: [4.3843767690508]
20250728: [4.326701331152087]
20250729: [4.452800330326276]
20250730: [4.401454249097702]
20250731: [4.310765769740332]
20250801: [5.538232020714296]
20250802: [4.382399890082247]
20250803: [4.347126484396598]
20250804: [4.343049790889712]
20250805: [4.4047123244990285]
20250806: [4.291651428773284]
20250807: [4.354215842476844]
20250808: [4.371614961002943]
20250809: [4.159248456758908]
20250810: [4.356261250954439]
20250811: [4.349966744326976]
20250812: [4.350923549158857]
20250813: [4.383173472455781]
20250814: [4.30714901604753]
20250815: [4.354675576652863]
20250816: [4.370699169757441]
20250817: [4.3393025051255885]
20250818: [4.357078000604603]
20250819: [4.346280562194852]
20250820: [4.37471338635658]
20250821: [4.279095105271722]
20250822: [4.137848902896936]
20250823: [4.331147414656203]
20250824: [4.37528328621479]
20250825: [4.275665403130723]
20250826: [4.200545814179286]
20250827: [4.258541300855679]
20250828: [4.1340051426145035]
20250829: [4.210100461388178]
20250830: [4.335624738381667]
20250831: [4.238602796822545]
20250901: [4.226496896666841]
20250902: [4.280490130475994]
20250903: [4.274405899034766]
20250904: [4.211947386922071]
20250905: [4.999195950903057]
20250906: [4.290185763840998]
20250907: [4.23747978080253]
20250908: [4.231893596500907]
20250909: [4.294978291144425]
20250910: [4.242244276871589]
20250911: [4.93820359244204]
20250912: [4.571103605679071]
20250913: [4.224366207069696]
20250914: [4.238379203346639]
20250915: [3.7774213201738265]
20250916: [4.257268029620803]
20250917: [4.276319566372199]
20250918: [4.188461358184168]
20250919: [4.174639653441813]
20250920: [4.239470122332357]
20250921: [4.258323705119068]
20250922: [4.232058458007539]
20250923: [4.219337494170786]
20250924: [4.267487543968473]
20250926: [4.2989273647141175]
20250927: [4.209748151756525]
20250928: [4.259717046948934]
20250929: [4.270394693345026]
20250930: [5.072788749231871]
20251001: [4.275463895247196]
20251002: [4.248824349759125]
20251003: [4.289369154529041]
20251004: [4.247388424637394]
20251005: [4.251412156647203]
20251006: [4.236207873279628]
20251007: [4.288437378173003]
20251008: [4.3452139245938355]
20251009: [4.239250956336895]
20251010: [4.305939726057457]
20251011: [4.1447592639481465]
20251012: [4.325721340626003]
20251013: [4.860221957695383]
20251014: [4.308243164544517]
20251015: [4.827475584521938]
20251016: [4.245665775877357]
20251017: [4.361403083743224]
20251018: [4.25743527925479]
20251019: [4.282615137593704]
20251020: [4.325622254211055]
20251021: [4.327637741183455]
20251022: [4.829062974482943]
20251023: [4.301671330321509]
20251024: [4.288354447600786]
20251025: [4.322450543100371]
20251026: [4.227280586522276]
20251027: [4.278600587659257]
20251028: [4.266919468916582]
20251029: [4.230466656943447]
20251030: [4.268751289282034]
20251031: [4.272288246891893]
20251101: [4.147263886174559]
20251102: [4.231805066302397]
20251103: [4.283687831896078]
20251104: [4.3134172308043395]
20251105: [4.3093415010361245]
20251106: [4.287243911837702]
20251107: [4.3059153095822085]
20251108: [4.232593862775341]
20251109: [4.291346772554931]
20251110: [4.262044671633145]
20251111: [4.247475692624076]
20251112: [4.270332023855627]
20251113: [4.242931844090258]
20251114: [4.304778782238709]
20251115: [4.2634087260354105]
20251117: [4.232545478264016]
20251118: [4.2286125172987505]
20251119: [4.268146163075724]
20251120: [4.254874835825965]
20251121: [4.379606341873267]
20251124: [4.423303975965715]
20251125: [4.4494397044676015]
20251126: [4.285851769302092]
20251127: [4.404138237319162]
20251128: [4.3302216745168725]
20251129: [4.308958795453872]
