20251028: [4.266919468916582]
20251029: [4.230466656943447]
20251030: [4.268751289282034]
20251031: [4.272288246891893]
20251101: [4.147263886174559]
20251102: [4.231805066302397]
20251103: [4.283687831896078]
20251104: [4.3134172308043395]
20251105: [4.3093415010361245]
20251106: [4.287243911837702]
20251107: [4.3059153095822085]
