20250823: [8.1135736984463]
20250824: [8.081414129314117]
20250825: [8.09441472612574]
20250826: [7.910902235342186]
20250827: [7.393476961206394]
20250828: [8.113284330108119]
20250829: [8.124920927553939]
20250830: [7.914418928777765]
20250831: [7.989949708957494]
20250901: [7.959855129607666]
20250902: [8.232136943321219]
20250903: [8.046359614096726]
20250904: [7.8245480666941205]
20250905: [8.075584587652585]
20250906: [8.104783301013589]
20250907: [7.8038192905573265]
20250908: [8.160993554244302]
20250909: [8.236545792451949]
20250910: [7.885214547985364]
20250911: [7.439953069076937]
20250912: [7.930921110506703]
20250913: [8.115561701821344]
20250914: [8.05163427336745]
20250915: [7.9343058855270785]
20250916: [8.060090910560827]
20250917: [7.900893382064183]
20250918: [7.964426856713222]
20250919: [7.980791191226535]
20250920: [7.912382002734304]
20250921: [8.080768473499868]
20250922: [7.976776027569612]
20250923: [7.912137823969049]
20250924: [8.103346280724029]
20250926: [8.050286049552893]
20250927: [7.6405813560710225]
20250928: [7.791139251803745]
20250929: [8.275961432022688]
20250930: [7.37592851196339]
20251001: [8.038333714809292]
20251002: [8.10145081018143]
20251003: [8.034953898282508]
20251004: [8.03619353998731]
20251005: [7.479728537877933]
20251006: [8.126602525241287]
20251007: [8.04125589983668]
20251008: [8.254281435172137]
20251009: [8.016544631592565]
20251010: [8.066643672957332]
20251011: [8.050671865642077]
20251012: [8.195528519175676]
20251013: [7.276691851023016]
20251014: [8.038394253558796]
20251015: [8.230938205470558]
20251016: [8.2205106314616]
20251017: [8.080507467108001]
20251018: [8.147574855783223]
20251019: [8.310009977969774]
20251020: [8.141161591221275]
20251021: [7.964251051185301]
20251022: [8.068299049094405]
20251023: [7.9712724067956096]
20251024: [8.053393063776308]
20251025: [7.9624825580445115]
20251026: [8.255337317073595]
20251027: [7.980585360455851]
20251028: [8.16033970983397]
20251029: [8.011323243861298]
20251030: [8.160996159411663]
20251031: [7.770382300365038]
20251101: [8.071240395864901]
20251102: [8.031155811308563]
20251103: [8.083219788480985]
20251104: [8.12721492608693]
20251105: [8.210923738592541]
20251106: [8.113835496485123]
20251107: [8.023810351862027]
20251108: [7.9633005597603255]
20251109: [8.0914152486242]
20251110: [7.982906702733695]
20251111: [8.127298956947188]
20251112: [7.9161211953781265]
20251113: [8.1084343538044]
20251114: [8.123020267768863]
20251115: [7.9950917097427]
20251117: [7.9099609380870355]
20251118: [8.233617610203872]
20251119: [8.113182075215978]
20251120: [8.441744561140096]
20251121: [8.907236729733839]
