20251023: [7.9712724067956096]
20251024: [8.053393063776308]
20251025: [7.9624825580445115]
20251026: [8.255337317073595]
20251027: [7.980585360455851]
20251028: [8.16033970983397]
20251029: [8.011323243861298]
20251030: [8.160996159411663]
20251031: [7.770382300365038]
20251101: [8.071240395864901]
20251102: [8.031155811308563]
20251103: [8.083219788480985]
20251104: [8.12721492608693]
20251105: [8.210923738592541]
20251106: [8.113835496485123]
20251107: [8.023810351862027]
20251108: [7.9633005597603255]
