20250708: [8.563541073328715]
20250709: [8.489827168495086]
20250710: [8.362375228906918]
20250711: [8.541621812369748]
20250712: [8.629417282658384]
20250713: [8.474411281815708]
20250714: [8.440902291254485]
20250715: [7.853887598269248]
20250716: [8.094749616839318]
20250717: [8.018502610694973]
20250718: [8.220475891049718]
20250719: [8.08302701658399]
20250720: [8.199212845137755]
20250721: [7.997468200148461]
20250722: [7.8213585910034435]
20250723: [8.071682589871644]
20250724: [8.02455620335091]
20250725: [8.012138756868648]
20250726: [7.937150212947877]
20250727: [8.094653564810049]
20250728: [8.133186793715877]
20250729: [8.081206968138963]
20250730: [7.813807132536757]
20250731: [8.046959739159458]
20250801: [7.9873915860016425]
20250802: [8.052007900724057]
20250803: [7.900916753202752]
20250804: [8.19936711934594]
20250805: [8.1258181521966]
20250806: [7.867725249834694]
20250807: [8.051918173860996]
20250808: [8.01261168938169]
20250809: [7.715410357400936]
20250810: [7.916940322692742]
20250811: [8.031368223762422]
20250812: [8.13591623040775]
20250813: [8.046690660763222]
20250814: [7.984028104349838]
20250815: [8.074701457495651]
20250816: [7.699558177164429]
20250817: [8.074438535552277]
20250818: [7.9574977526521256]
20250819: [8.01888143373479]
20250820: [8.078771218682682]
20250821: [8.118495015315737]
20250822: [8.15516661061996]
20250823: [8.1135736984463]
20250824: [8.081414129314117]
20250825: [8.09441472612574]
20250826: [7.910902235342186]
20250827: [7.393476961206394]
20250828: [8.113284330108119]
20250829: [8.124920927553939]
20250830: [7.914418928777765]
20250831: [7.989949708957494]
20250901: [7.959855129607666]
20250902: [8.232136943321219]
20250903: [8.046359614096726]
20250904: [7.8245480666941205]
20250905: [8.075584587652585]
20250906: [8.104783301013589]
20250907: [7.8038192905573265]
20250908: [8.160993554244302]
20250909: [8.236545792451949]
20250910: [7.885214547985364]
20250911: [7.439953069076937]
20250912: [7.930921110506703]
20250913: [8.115561701821344]
20250914: [8.05163427336745]
20250915: [7.9343058855270785]
20250916: [8.060090910560827]
20250917: [7.900893382064183]
20250918: [7.964426856713222]
20250919: [7.980791191226535]
20250920: [7.912382002734304]
20250921: [8.080768473499868]
20250922: [7.976776027569612]
20250923: [7.912137823969049]
20250924: [8.103346280724029]
20250926: [8.050286049552893]
20250927: [7.6405813560710225]
20250928: [7.791139251803745]
20250929: [8.275961432022688]
20250930: [7.37592851196339]
20251001: [8.038333714809292]
20251002: [8.10145081018143]
20251003: [8.034953898282508]
20251004: [8.03619353998731]
20251005: [7.479728537877933]
20251006: [8.126602525241287]
20251007: [8.04125589983668]
20251008: [8.254281435172137]
20251009: [8.016544631592565]
20251010: [8.066643672957332]
20251011: [8.050671865642077]
20251012: [8.195528519175676]
20251013: [7.276691851023016]
20251014: [8.038394253558796]
20251015: [8.230938205470558]
20251016: [8.2205106314616]
20251017: [8.080507467108001]
20251018: [8.147574855783223]
20251019: [8.310009977969774]
20251020: [8.141161591221275]
20251021: [7.964251051185301]
20251022: [8.068299049094405]
20251023: [7.9712724067956096]
20251024: [8.053393063776308]
20251025: [7.9624825580445115]
20251026: [8.255337317073595]
20251027: [7.980585360455851]
20251028: [8.16033970983397]
20251029: [8.011323243861298]
20251030: [8.160996159411663]
20251031: [7.770382300365038]
20251101: [8.071240395864901]
20251102: [8.031155811308563]
20251103: [8.083219788480985]
20251104: [8.12721492608693]
20251105: [8.210923738592541]
20251106: [8.113835496485123]
20251107: [8.023810351862027]
20251108: [7.9633005597603255]
20251109: [8.0914152486242]
20251110: [7.982906702733695]
20251111: [8.127298956947188]
20251112: [7.9161211953781265]
20251113: [8.1084343538044]
20251114: [8.123020267768863]
20251115: [7.9950917097427]
20251117: [7.9099609380870355]
20251118: [8.233617610203872]
20251119: [8.113182075215978]
20251120: [8.441744561140096]
20251121: [8.907236729733839]
20251124: [8.731018207183993]
20251125: [9.147736485591365]
20251126: [8.864986177781681]
20251127: [9.15388727951645]
20251128: [8.615488821082437]
20251129: [8.981655935356812]
20251130: [8.757986194160246]
20251201: [8.733431295998692]
20251202: [8.813455962525039]
20251203: [8.70024901659496]
20251204: [8.22529565442314]
20251205: [8.225045389956987]
20251206: [9.28277331524054]
20251207: [9.120922600132142]
20251208: [9.154036648446663]
20251209: [9.086508962992227]
20251210: [8.546084971852823]
20251211: [7.8259724293939215]
20251212: [8.268347215227175]
20251213: [8.729353257759282]
20251214: [8.506966488120025]
20251215: [8.639221975393603]
20251216: [9.120398569931]
20251217: [8.607099627501931]
20251218: [8.689885516168806]
20251219: [8.417193050637247]
20251220: [8.689654283872349]
20251221: [8.180917388509075]
20251222: [8.666935250207912]
20251223: [8.681484386905549]
20251224: [8.780171979345575]
20251225: [8.248122117782682]
20251226: [8.41435065403218]
20251227: [8.901588461695976]
20251228: [8.862783683254518]
20251229: [9.049985462599503]
20251230: [9.014678855025062]
20251231: [8.993515807902702]
20260101: [8.821071070779137]
20260102: [8.838362143828373]
20260103: [8.863652550033027]
20260104: [8.853285411415944]
20260105: [9.003671597359348]
20260106: [8.963729722678497]
20260107: [8.583091190396802]
20260108: [9.051250166084856]
20260109: [8.936658347639032]
20260110: [8.420466307997163]
20260111: [8.477370038065754]
20260112: [8.858724596305155]
20260113: [9.066322705284641]
20260114: [9.118143696041514]
20260115: [8.294589860752108]
20260116: [8.961242753522978]
20260117: [8.226583383613878]
20260119: [9.076611154493206]
